# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applying_class', models.CharField(max_length=6)),
                ('ubit_name', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gpa', models.FloatField()),
                ('class_grade', models.CharField(max_length=2)),
                ('resume_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_identifier', models.CharField(max_length=6)),
                ('professor_ubit', models.CharField(max_length=10)),
                ('professor_first_name', models.CharField(max_length=30)),
                ('professor_last_name', models.CharField(max_length=30)),
                ('available_slots', models.IntegerField()),
            ],
        ),
    ]
